### ISSUE TITLE
Another: Conventional Commits

### ISSUE THREAD

**Issue by ghost** [janu8ry/kkutbot#13]
현재 끝봇 리포지토리의 커밋 내역을 보면 뒤죽박죽 섞여 있어 커밋에 대한 이해가 힘들다는 단점이 있습니다
따라서 https://www.conventionalcommits.org/ko/v1.0.0/ 를 준수하여 커밋을 하면 좋을 것 같습니다

**Comment by janu8ry** [comment]
반영하겠습니다
